export default {
  name: "consultationModal",
  title: "Consultation Modal",
  type: "object",
  fields: [
    { name: "tagline", title: "Tagline", type: "string" },
    { name: "heading", title: "Heading", type: "string" },
    { name: "subheading", title: "Subheading", type: "text" },
    {
      name: "fullNameLabel",
      title: "Full Name Label",
      type: "string",
      initialValue: "Full Name",
    },
    {
      name: "fullNamePlaceholder",
      title: "Full Name Placeholder",
      type: "string",
      initialValue: "Jane Smith",
    },
    {
      name: "emailLabel",
      title: "Email Label",
      type: "string",
      initialValue: "Email",
    },
    {
      name: "emailPlaceholder",
      title: "Email Placeholder",
      type: "string",
      initialValue: "you@example.com",
    },
    {
      name: "phoneLabel",
      title: "Phone Label",
      type: "string",
      initialValue: "Phone Number",
    },
    {
      name: "phonePlaceholder",
      title: "Phone Placeholder",
      type: "string",
      initialValue: "+61 400 000 000",
    },
    {
      name: "defaultPhonePrefix",
      title: "Default Phone Prefix",
      type: "string",
      initialValue: "+61 ",
    },
    {
      name: "interestLabel",
      title: "Interest Label",
      type: "string",
      initialValue: "Interest",
    },
    {
      name: "interestPlaceholder",
      title: "Interest Placeholder",
      type: "string",
      initialValue: "Select an option",
    },
    {
      name: "interestOptions",
      title: "Interest Options",
      type: "array",
      of: [{ type: "string" }],
      validation: (Rule) => Rule.min(1),
    },
    {
      name: "consentPrefix",
      title: "Consent Prefix",
      type: "string",
      initialValue: "I agree to the",
    },
    {
      name: "termsLabel",
      title: "Terms Label",
      type: "string",
      initialValue: "Terms",
    },
    {
      name: "termsLink",
      title: "Terms Link",
      type: "string",
      initialValue: "#",
    },
    {
      name: "privacyLabel",
      title: "Privacy Label",
      type: "string",
      initialValue: "Privacy Policy",
    },
    {
      name: "privacyLink",
      title: "Privacy Link",
      type: "string",
      initialValue: "#",
    },
    {
      name: "submitButtonText",
      title: "Submit Button Text",
      type: "string",
      initialValue: "Book My Consultation",
    },
    {
      name: "submittingButtonText",
      title: "Submitting Button Text",
      type: "string",
      initialValue: "Submitting...",
    },
    {
      name: "successHeading",
      title: "Success Heading",
      type: "string",
      initialValue: "Thank you!",
    },
    {
      name: "successMessage",
      title: "Success Message",
      type: "text",
      initialValue:
        "Your consultation request has been received. A MARA-registered advisor will reach out within 1 business day.",
    },
    {
      name: "successCloseText",
      title: "Success Close Button Text",
      type: "string",
      initialValue: "Close",
    },
  ],
};
